version: '3'
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-crawler
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drogasil
      MYSQL_USER: sb-user
      MYSQL_PASSWORD: daniella
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3301:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
      - ./grant-usage.sql:/docker-entrypoint-initdb.d/grant-usage.sql